### ISSUE TITLE
The 3rd screenshot doesn't get shown on the main page

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-MessagingService#3]
This:
https://github.com/googlesamples/android-MessagingService/raw/master/screenshots/3-threemessages.png

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
