### ISSUE TITLE
Does not work with Android O 

### ISSUE THREAD

**Issue by masbaehr** [googlesamples/android-MessagingService#4]
Need to create notificationchannnel:

 @TargetApi(Build.VERSION_CODES.O)
    public static void createNotificationChannelIfNotSet(Context context, String channelId, String channelName){
        NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        assert notificationManager != null;
        NotificationChannel channelCheck = notificationManager.getNotificationChannel(channelId);

and use the channel here:

        NotificationCompat.Builder builder =
                new NotificationCompat.Builder(getApplicationContext(), "XXXXXXXXXXX")
        if(channelCheck == null) {
            int importance = NotificationManager.IMPORTANCE_LOW;
            NotificationChannel notificationChannel = new NotificationChannel(channelId, channelName, importance);
            notificationManager.createNotificationChannel(notificationChannel);
        }
    }

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
