### ISSUE TITLE
No implicit Intend on Android 26+

### ISSUE THREAD

**Issue by janfkoester** [googlesamples/android-MessagingService#6]
The intend for the read and replay doesn't work with the current code for android 26+ because the intent is not explicit and implicit intends are not allowed in this way any more.

see https://developer.android.com/guide/components/broadcasts 
"If your app targets API level 26 or higher, you cannot use the manifest to declare a receiver for implicit broadcasts (broadcasts that do not target your app specifically), except for a few implicit broadcasts that are exempted from that restriction. In most cases, you can use scheduled jobs instead." 

this code works for me on android 26+
```
    // Creates an intent that will be triggered when a message is marked as read.
    private Intent getMessageReadIntent(int id) {
        return new Intent(getApplicationContext(), MessageReadReceiver.class)
                .addFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES)
                .setAction(READ_ACTION)
                .putExtra(CONVERSATION_ID, id);
    }

    // Creates an Intent that will be triggered when a voice reply is received.
    private Intent getMessageReplyIntent(int conversationId) {
        return new Intent(getApplicationContext(), MessageReplyReceiver.class)
                .addFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES)
                .setAction(REPLY_ACTION)
                .putExtra(CONVERSATION_ID, conversationId);
    }
```

The MessageReplyReceiver.class and MessageReadReceiver.class must be provided in the Intend constructor

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
